// ============================================================
// data-fndex.js — สารบัญฟังก์ชันทั้งระบบ (All Functions Directory)
// ครบทุกฟังก์ชันหลักและย่อยจาก 10 ไฟล์ (คน 1-6)
// พร้อมเลขบรรทัดจริง, บทบาทหน้าที่, และปุ่มกดส่องโค้ดเร็ว
// ============================================================

const ALL_FUNCTIONS_DIRECTORY = [
  {
    name: "computeCacheKey",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 10,
    owner: "คน 6",
    category: "Security & Cache",
    badge: "คน 6: Core Pipeline",
    signature: "function computeCacheKey(githubUrl: string, token?: string): string",
    desc: "คำนวณคีย์แคชแบบแบ่งส่วน (Partitioned Cache Key) ด้วย SHA-256 Token Hash ป้องกันการข้ามสิทธิ์และป้องกัน Cache Poisoning",
    tags: ["cache", "security", "sha256", "token", "partition"],
    snippet: "function computeCacheKey(githubUrl: string, token?: string): string"
  },
  // --- คน 1: GitHub Service (src/lib/github.ts) ---
  {
    name: "parseGitHubUrl",
    file: "github",
    filePath: "src/lib/github.ts",
    line: 15,
    owner: "คน 1",
    category: "URL & API Parsing",
    badge: "คน 1: GitHub Service",
    signature: "export function parseGitHubUrl(url: string): ParsedGitHubUrl | null",
    desc: "แกะและตรวจความถูกต้องของ URL GitHub ตรวจโดเมน github.com ตัด .git และแยก owner, repo และ branch ออกมา",
    tags: ["url", "github", "regex", "parsing"],
    snippet: "export function parseGitHubUrl(url: string): ParsedGitHubUrl | null"
  },
  {
    name: "buildGitHubApiUrl",
    file: "github",
    filePath: "src/lib/github.ts",
    line: 44,
    owner: "คน 1",
    category: "URL & API Parsing",
    badge: "คน 1: GitHub Service",
    signature: "export function buildGitHubApiUrl(owner: string, repo: string, branch = 'main'): string",
    desc: "ประกอบ REST API Endpoint สำหรับดึง Git Trees แบบ recursive (?recursive=1) ทั้งโปรเจกต์ในคำขอเดียว",
    tags: ["api", "github", "trees", "endpoint"],
    snippet: "export function buildGitHubApiUrl(owner: string, repo: string, branch = 'main'): string"
  },
  {
    name: "buildGitHubHeaders",
    file: "github",
    filePath: "src/lib/github.ts",
    line: 51,
    owner: "คน 1",
    category: "HTTP & Auth",
    badge: "คน 1: GitHub Service",
    signature: "export function buildGitHubHeaders(token?: string): Record<string, string>",
    desc: "สร้าง HTTP Headers แนบ User-Agent และใส่ Bearer Token เมื่อผู้ใช้กรอก GitHub Personal Access Token",
    tags: ["headers", "token", "auth", "http"],
    snippet: "export function buildGitHubHeaders(token?: string): Record<string, string>"
  },
  {
    name: "buildGitHubRawUrl",
    file: "github",
    filePath: "src/lib/github.ts",
    line: 66,
    owner: "คน 1",
    category: "Raw Content",
    badge: "คน 1: GitHub Service",
    signature: "export function buildGitHubRawUrl(owner: string, repo: string, filePathOrBranch: string, branchOrPath = 'main'): string",
    desc: "สร้าง URL สำหรับดึงโค้ดดิบ (Raw Content) จาก raw.githubusercontent.com เพื่อใช้วิเคราะห์ imports และ actions",
    tags: ["raw", "cdn", "download", "content"],
    snippet: "export function buildGitHubRawUrl(owner: string, repo: string, filePathOrBranch: string, branchOrPath = 'main'): string"
  },
  {
    name: "buildGitHubBlobUrl",
    file: "github",
    filePath: "src/lib/github.ts",
    line: 82,
    owner: "คน 1",
    category: "Navigation Link",
    badge: "คน 1: GitHub Service",
    signature: "export function buildGitHubBlobUrl(owner: string, repo: string, filePath: string, branch = 'main'): string",
    desc: "สร้างลิงก์สำหรับคลิกเปิดดูไฟล์ต้นฉบับบนเว็บ github.com/blob โดยตรงจากแผง SideDrawer",
    tags: ["blob", "link", "github.com", "ui"],
    snippet: "export function buildGitHubBlobUrl(owner: string, repo: string, filePath: string, branch = 'main'): string"
  },

  // --- คน 2: Parser Engine (src/lib/parser.ts) ---
  {
    name: "shouldIgnorePath",
    file: "parser",
    filePath: "src/lib/parser.ts",
    line: 76,
    owner: "คน 2",
    category: "Filtering & Sanitization",
    badge: "คน 2: Parser Engine",
    signature: "function shouldIgnorePath(lowerPath: string, fileName: string, isRootFile: boolean): boolean",
    desc: "ฟังก์ชันกรอง Blacklist ตรวจสอบว่าไฟล์อยู่ในโฟลเดอร์ขยะ เช่น node_modules, .next, dist หรือเป็น lockfile หรือไม่ (ยกเว้น middleware/proxy ที่รูท)",
    tags: ["filter", "blacklist", "sanitize", "ignore"],
    snippet: "function shouldIgnorePath(lowerPath: string, fileName: string, isRootFile: boolean): boolean"
  },
  {
    name: "filterTreeFiles",
    file: "parser",
    filePath: "src/lib/parser.ts",
    line: 101,
    owner: "คน 2",
    category: "Filtering & Sanitization",
    badge: "คน 2: Parser Engine",
    signature: "export function filterTreeFiles(items: GitHubTreeItem[], maxLimit = 250): GitHubTreeItem[]",
    desc: "คัดกรองไฟล์ทั้งคลัง รับเฉพาะไฟล์โค้ด (.ts, .tsx, .js, .jsx) ที่ผ่าน Blacklist และจำกัดจำนวนสูงสุดตาม maxLimit (ค่าเริ่มต้น 250 ไฟล์, pipeline ส่ง 500)",
    tags: ["filter", "tree", "limit", "whitelist"],
    snippet: "export function filterTreeFiles(items: GitHubTreeItem[], maxLimit = 250): GitHubTreeItem[]"
  },
  {
    name: "detectNextFileType",
    file: "parser",
    filePath: "src/lib/parser.ts",
    line: 129,
    owner: "คน 2",
    category: "App Router Classification",
    badge: "คน 2: Parser Engine",
    signature: "export function detectNextFileType(filePath: string): NextFileType",
    desc: "จำแนกประเภทไฟล์ Next.js App Router ออกเป็น 8 ประเภท: page, layout, action, middleware, store, api, component, other",
    tags: ["classify", "filetype", "app-router", "detection"],
    snippet: "export function detectNextFileType(filePath: string): NextFileType"
  },
  {
    name: "extractImportsFromCode",
    file: "parser",
    filePath: "src/lib/parser.ts",
    line: 165,
    owner: "คน 2",
    category: "AST & Code Analysis",
    badge: "คน 2: Parser Engine",
    signature: "export function extractImportsFromCode(sourcePath: string, codeContent: string): CodeRelation[]",
    desc: "สแกนซอร์สโค้ดด้วย Regex หาคำสั่ง import/from และแกะพาธเป้าหมาย พร้อมระบุชนิดความสัมพันธ์เป็น imports",
    tags: ["import", "regex", "relation", "dependencies"],
    snippet: "export function extractImportsFromCode(sourcePath: string, codeContent: string): CodeRelation[]"
  },
  {
    name: "extractTargetFunction",
    file: "parser",
    filePath: "src/lib/parser.ts",
    line: 195,
    owner: "คน 2",
    category: "AST & Code Analysis",
    badge: "คน 2: Parser Engine",
    signature: "function extractTargetFunction(expression: string): string | null",
    desc: "ถอดชื่อฟังก์ชันเป้าหมายออกจาก JSX attribute handler เช่น onClick={() => mutate()} หรือ action={handleSubmit}",
    tags: ["handler", "jsx", "function-name", "target"],
    snippet: "function extractTargetFunction(expression: string): string | null"
  },
  {
    name: "extractActionTriggers",
    file: "parser",
    filePath: "src/lib/parser.ts",
    line: 213,
    owner: "คน 2",
    category: "AST & Code Analysis",
    badge: "คน 2: Parser Engine",
    signature: "export function extractActionTriggers(sourcePath: string, codeContent: string): CodeRelation[]",
    desc: "ตรวจจับ Server Action หรือ Event Trigger จาก onClick, onSubmit, action={...} และสร้าง CodeRelation แบบ action_trigger",
    tags: ["action", "event", "server-action", "trigger"],
    snippet: "export function extractActionTriggers(sourcePath: string, codeContent: string): CodeRelation[]"
  },

  // --- คน 3: Flow Generator & Canvas (src/lib/generator.ts & src/components/FlowCanvas.tsx) ---
  {
    name: "sanitizeNodeId",
    file: "generator",
    filePath: "src/lib/generator.ts",
    line: 7,
    owner: "คน 3",
    category: "Graph Building",
    badge: "คน 3: Flow Generator",
    signature: "export function sanitizeNodeId(pathStr: string): string",
    desc: "แปลง path ของไฟล์ให้เป็น Node ID ที่ปลอดภัยสำหรับ Mermaid และ React Flow โดยแทนที่เครื่องหมายพิเศษด้วยขีดล่าง _",
    tags: ["id", "sanitize", "graph", "mermaid"],
    snippet: "export function sanitizeNodeId(pathStr: string): string"
  },
  {
    name: "getNodeColorConfig",
    file: "generator",
    filePath: "src/lib/generator.ts",
    line: 30,
    owner: "คน 3",
    category: "Theming & Colors",
    badge: "คน 3: Flow Generator",
    signature: "export function getNodeColorConfig(fileType: NextFileType): { border: string; bg: string; text: string }",
    desc: "กำหนดชุดสีพื้นหลัง เส้นขอบ และข้อความของโหนดบนแผนผังตามประเภทไฟล์ (Page, Action, Component, Store ฯลฯ)",
    tags: ["theme", "colors", "nodes", "styling"],
    snippet: "export function getNodeColorConfig(fileType: NextFileType): { border: string; bg: string; text: string }"
  },
  {
    name: "applyDagreLayout",
    file: "generator",
    filePath: "src/lib/generator.ts",
    line: 40,
    owner: "คน 3",
    category: "Graph Layout",
    badge: "คน 3: Flow Generator",
    signature: "function applyDagreLayout(nodes: FlowNodeItem[], edges: FlowEdgeItem[], seenIds: Set<string>): void",
    desc: "จัดผังโหนดด้วย Dagre Graph Algorithm แบบลำดับชั้นบนลงล่าง (Top-to-Bottom / TB) กำหนด nodeSep=50, rankSep=100 ป้องกันเส้นพันกัน",
    tags: ["dagre", "layout", "hierarchy", "graph"],
    snippet: "function applyDagreLayout(nodes: FlowNodeItem[], edges: FlowEdgeItem[], seenIds: Set<string>): void"
  },
  {
    name: "buildFlowElements",
    file: "generator",
    filePath: "src/lib/generator.ts",
    line: 89,
    owner: "คน 3",
    category: "Graph Building",
    badge: "คน 3: Flow Generator",
    signature: "export function buildFlowElements(relations: CodeRelation[], fileTypes?: Map<string, NextFileType>): { nodes: FlowNodeItem[]; edges: FlowEdgeItem[] }",
    desc: "แปลงชุด CodeRelation เป็น React Flow Nodes และ Edges พร้อมดึงประเภทไฟล์เพื่อกำหนดสี แล้วส่งต่อเข้า Dagre เพื่อจัดพิกัด (x, y)",
    tags: ["elements", "nodes", "edges", "reactflow"],
    snippet: "export function buildFlowElements(relations: CodeRelation[], fileTypes?: Map<string, NextFileType>): { nodes: FlowNodeItem[]; edges: FlowEdgeItem[] }"
  },
  {
    name: "generateMermaidSyntax",
    file: "generator",
    filePath: "src/lib/generator.ts",
    line: 169,
    owner: "คน 3",
    category: "Mermaid Export",
    badge: "คน 3: Flow Generator",
    signature: "export function generateMermaidSyntax(relations: CodeRelation[]): string",
    desc: "แปลงรายการความสัมพันธ์เป็นโค้ดไดอะแกรม Mermaid syntax (flowchart TD) สำหรับนำไปใช้ใน Markdown หรือส่งออกภายนอก",
    tags: ["mermaid", "export", "markdown", "syntax"],
    snippet: "export function generateMermaidSyntax(relations: CodeRelation[]): string"
  },
  {
    name: "computeTracePath",
    file: "flowcanvas",
    filePath: "src/components/FlowCanvas.tsx",
    line: 48,
    owner: "คน 3",
    category: "Canvas Interaction",
    badge: "คน 3: Flow Canvas (Visualizer)",
    signature: "function computeTracePath(selectedId: string, edges: FlowEdgeItem[]): { nodeIds: Set<string>; edgeIds: Set<string> }",
    desc: "คำนวณ Path ความสัมพันธ์ย้อนกลับ (Upstream/Dependencies) และตามน้ำ (Downstream/Dependents) ของโหนดที่คลิกเลือก",
    tags: ["trace", "highlight", "upstream", "downstream"],
    snippet: "function computeTracePath(selectedId: string, edges: FlowEdgeItem[]): { nodeIds: Set<string>; edgeIds: Set<string> }"
  },
  {
    name: "toRfNodes",
    file: "flowcanvas",
    filePath: "src/components/FlowCanvas.tsx",
    line: 122,
    owner: "คน 3",
    category: "Canvas Rendering",
    badge: "คน 3: Flow Canvas (Visualizer)",
    signature: "function toRfNodes(nodes: FlowNodeItem[], activePath: Set<string>, labelMode: LabelMode): Node[]",
    desc: "แปลง FlowNodeItem ให้เป็นโครงสร้าง Node ของ React Flow พร้อมกำหนด Handle พิกัด และระดับความโปร่งใสตามสถานะการไฮไลต์",
    tags: ["reactflow", "nodes", "rendering", "handles"],
    snippet: "function toRfNodes(nodes: FlowNodeItem[], activePath: Set<string>, labelMode: LabelMode): Node[]"
  },
  {
    name: "toRfEdges",
    file: "flowcanvas",
    filePath: "src/components/FlowCanvas.tsx",
    line: 224,
    owner: "คน 3",
    category: "Canvas Rendering",
    badge: "คน 3: Flow Canvas (Visualizer)",
    signature: "function toRfEdges(edges: FlowEdgeItem[], activePath: Set<string>, labelMode: LabelMode): Edge[]",
    desc: "แปลง FlowEdgeItem ให้เป็น Edge ของ React Flow พร้อมกำหนดสีเส้น, ลูกศร markerEnd, เส้นประ/เส้นทึบ และแอนิเมชัน animated",
    tags: ["reactflow", "edges", "arrows", "animation"],
    snippet: "function toRfEdges(edges: FlowEdgeItem[], activePath: Set<string>, labelMode: LabelMode): Edge[]"
  },
  {
    name: "FlowCanvasInner",
    file: "flowcanvas",
    filePath: "src/components/FlowCanvas.tsx",
    line: 290,
    owner: "คน 3",
    category: "Canvas Component",
    badge: "คน 3: Flow Canvas (Visualizer)",
    signature: "function FlowCanvasInner({ nodes, edges, onSelectNode }: FlowCanvasProps)",
    desc: "คอมโพเนนต์แกนหลักของ React Flow จัดการ State การซูม, แพน, ค้นหาด่วน (Node Finder), ยุบ/ขยาย MiniMap และสลับโหมดป้ายกำกับ",
    tags: ["canvas", "react", "pan-zoom", "controls"],
    snippet: "function FlowCanvasInner({ nodes, edges, onSelectNode }: FlowCanvasProps)"
  },
  {
    name: "handleGlobalKeyDown",
    file: "flowcanvas",
    filePath: "src/components/FlowCanvas.tsx",
    line: 373,
    owner: "คน 3",
    category: "Keyboard Navigation",
    badge: "คน 3: Flow Canvas (Visualizer)",
    signature: "const handleGlobalKeyDown = (e: KeyboardEvent) => void",
    desc: "ตรวจจับคีย์ลัดระดับ Global เช่น Ctrl+K (เปิดกล่องค้นหาโหนดด่วน), Escape (ล้างการเลือก/ปิดกล่องค้นหา) เพื่อความสะดวกในการใช้งาน",
    tags: ["shortcut", "ctrl-k", "escape", "keyboard"],
    snippet: "const handleGlobalKeyDown = (e: KeyboardEvent) => void"
  },

  // --- คน 4: Dashboard UI & Helpers (src/app/page.tsx, src/components/FlowExplorer.tsx & src/lib/ui-helper.ts) ---
  {
    name: "HomePage",
    file: "page",
    filePath: "src/app/page.tsx",
    line: 5,
    owner: "คน 4",
    category: "Page Entry Point",
    badge: "คน 4: Dashboard UI",
    signature: "export default function HomePage(): JSX.Element",
    desc: "คอมโพเนนต์หน้าแรกแบบ Thin Server Wrapper วางส่วนหัว Navbar, โลโก้ และติดตั้ง FlowExplorer",
    tags: ["page", "entry", "wrapper", "navbar"],
    snippet: "export default function HomePage() {"
  },
  {
    name: "FlowExplorer",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 25,
    owner: "คน 4",
    category: "State Engine & Orchestrator",
    badge: "คน 4: State Orchestrator",
    signature: "export function FlowExplorer(): JSX.Element",
    desc: "คอมโพเนนต์บริหารจัดการ State กลางของ UI ฝั่ง Client: คุม Form ค้นหา, Filter แท็บ, ดึงโค้ดสด และเชื่อมต่อ FlowCanvas กับ SideDrawer",
    tags: ["explorer", "orchestrator", "state", "client"],
    snippet: "export function FlowExplorer() {"
  },
  {
    name: "handleSelectNode",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 43,
    owner: "คน 4",
    category: "Dashboard State & Fetch",
    badge: "คน 4: State Orchestrator",
    signature: "async function handleSelectNode(filePath: string, fileType: NextFileType, ...): Promise<void>",
    desc: "ทำงานเมื่อผู้ใช้คลิกโหนดบนแผนผัง: ดึงโค้ดดิบจาก GitHub Raw CDN และเปิดแผง SideDrawer ของคน 5 ขึ้นมาแสดงผล",
    tags: ["node-click", "fetch-code", "sidedrawer", "inspect"],
    snippet: "async function handleSelectNode(filePath: string, fileType: NextFileType, ...): Promise<void>"
  },
  {
    name: "executeAnalysis",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 103,
    owner: "คน 4",
    category: "Dashboard State & Fetch",
    badge: "คน 4: State Orchestrator",
    signature: "const executeAnalysis = async (targetUrl: string, githubToken?: string, activeFileFilter?: string): Promise<void>",
    desc: "ฟังก์ชันยิง API กลาง: ส่งคำขอ POST /api/analyze พร้อมจัดการสถานะกำลังโหลด, ข้อความผิดพลาด, และอัปเดตสถิติคลัง",
    tags: ["fetch", "api-call", "loading-state", "analyze"],
    snippet: "const executeAnalysis = async (targetUrl: string, githubToken?: string, activeFileFilter?: string): Promise<void>"
  },
  {
    name: "handleSubmit",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 168,
    owner: "คน 4",
    category: "Form Handler",
    badge: "คน 4: State Orchestrator",
    signature: "const handleSubmit = (e: React.FormEvent) => void",
    desc: "ดักจับการ Submit ของฟอร์ม ตรวจสอบความถูกต้องของ URL เบื้องต้น แล้วเรียก executeAnalysis",
    tags: ["form", "submit", "event", "validation"],
    snippet: "const handleSubmit = (e: React.FormEvent) => void"
  },
  {
    name: "handleShare",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 173,
    owner: "คน 4",
    category: "Sharing",
    badge: "คน 4: State Orchestrator",
    signature: "const handleShare = () => void",
    desc: "เข้ารหัสสถานะปัจจุบัน (URL + โหนดที่เลือก) ด้วย encodeShareableState และคัดลอก Share Link ลง Clipboard",
    tags: ["share", "clipboard", "url-state", "base64"],
    snippet: "const handleShare = () => void"
  },
  {
    name: "displayedNodes",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 200,
    owner: "คน 4",
    category: "Tab Filtering",
    badge: "คน 4: State Orchestrator",
    signature: "const displayedNodes = useMemo(() => FlowNodeItem[], [result, filterType])",
    desc: "กรองโหนดที่แสดงผลตามแท็บที่ผู้ใช้เลือก: ALL, PAGE (รวม middleware), ACTION (รวม api), COMPONENT, STORE",
    tags: ["filter", "useMemo", "tabs", "nodes"],
    snippet: "const displayedNodes = useMemo(() => FlowNodeItem[], [result, filterType])"
  },
  {
    name: "displayedEdges",
    file: "flowexplorer",
    filePath: "src/components/FlowExplorer.tsx",
    line: 212,
    owner: "คน 4",
    category: "Tab Filtering",
    badge: "คน 4: State Orchestrator",
    signature: "const displayedEdges = useMemo(() => FlowEdgeItem[], [result, displayedNodes, filterType])",
    desc: "กรองเส้นเชื่อมให้แสดงเฉพาะเส้นที่ทั้งโหนดต้นทางและปลายทางยังปรากฏอยู่บนหน้าจอหลังจากถูกกรองด้วย filterType",
    tags: ["filter", "useMemo", "edges", "activeIds"],
    snippet: "const displayedEdges = useMemo(() => FlowEdgeItem[], [result, displayedNodes, filterType])"
  },
  {
    name: "validateUrlInput",
    file: "uihelper",
    filePath: "src/lib/ui-helper.ts",
    line: 4,
    owner: "คน 4",
    category: "Validation & Stats",
    badge: "คน 4: UI Helper & URL Guard",
    signature: "export function validateUrlInput(input: string): { isValid: boolean; errorMessage?: string }",
    desc: "ตรวจสอบ URL หน้าบ้าน เช็กค่าว่าง, โดเมน github.com, โครงสร้าง owner/repo และกันช่องโหว่ XSS/Injection",
    tags: ["validation", "guard", "input", "url"],
    snippet: "export function validateUrlInput(input: string): { isValid: boolean; errorMessage?: string }"
  },
  {
    name: "formatRepoStats",
    file: "uihelper",
    filePath: "src/lib/ui-helper.ts",
    line: 44,
    owner: "คน 4",
    category: "Validation & Stats",
    badge: "คน 4: UI Helper & URL Guard",
    signature: "export function formatRepoStats(totalFiles: number, filteredFiles: number): { displayTotal: string; filterRatio: string }",
    desc: "คำนวณและจัดรูปแบบตัวเลขสถิติของคลัง: จำนวนไฟล์ทั้งหมด และสัดส่วนไฟล์ที่ผ่านเกณฑ์การกรอง",
    tags: ["stats", "ratio", "formatting", "numbers"],
    snippet: "export function formatRepoStats(totalFiles: number, filteredFiles: number): { displayTotal: string; filterRatio: string }"
  },
  {
    name: "calculateHealthScore",
    file: "uihelper",
    filePath: "src/lib/ui-helper.ts",
    line: 85,
    owner: "คน 4",
    category: "Validation & Stats",
    badge: "คน 4: UI Helper & URL Guard",
    signature: "export function calculateHealthScore(totalRelations: number, filteredFiles: number): { score: number; label: string; color: string }",
    desc: "ประเมินระดับความเชื่อมโยงของสถาปัตยกรรม (Architectural Coupling) ออกมาเป็นคะแนนและป้ายกำกับสุขภาพระบบ",
    tags: ["health", "score", "coupling", "metrics"],
    snippet: "export function calculateHealthScore(totalRelations: number, filteredFiles: number): { score: number; label: string; color: string }"
  },
  {
    name: "encodeShareableState",
    file: "uihelper",
    filePath: "src/lib/ui-helper.ts",
    line: 63,
    owner: "คน 4",
    category: "Share Link",
    badge: "คน 4: UI Helper & URL Guard",
    signature: "export function encodeShareableState(url: string, activeNode?: string): string",
    desc: "เข้ารหัส URL และโหนดที่กำลังโฟกัสเป็น Base64 Safe String เพื่อสร้าง Shareable Link ให้ส่งต่อให้เพื่อนได้",
    tags: ["encode", "base64", "share", "state"],
    snippet: "export function encodeShareableState(url: string, activeNode?: string): string"
  },
  {
    name: "decodeShareableState",
    file: "uihelper",
    filePath: "src/lib/ui-helper.ts",
    line: 87,
    owner: "คน 4",
    category: "Share Link",
    badge: "คน 4: UI Helper & URL Guard",
    signature: "export function decodeShareableState(encodedStr: string): { url: string; activeNode?: string } | null",
    desc: "ถอดรหัส Base64 จาก URL Parameter เพื่อคืนค่าสถานะเดิมที่เพื่อนแชร์มาให้",
    tags: ["decode", "base64", "restore", "state"],
    snippet: "export function decodeShareableState(encodedStr: string): { url: string; activeNode?: string } | null"
  },

  // --- คน 5: Side Drawer & Code Viewer (src/components/SideDrawer.tsx & src/lib/code-viewer.ts) ---
  {
    name: "SideDrawer",
    file: "sidedrawer",
    filePath: "src/components/SideDrawer.tsx",
    line: 20,
    owner: "คน 5",
    category: "Inspector UI",
    badge: "คน 5: Side Drawer (Inspector)",
    signature: "export function SideDrawer({ isOpen, onClose, filePath, fileType, codeContent, isLoading, error }: SideDrawerProps)",
    desc: "คอมโพเนนต์แผงสไลด์ด้านข้างสำหรับเปิดดูโค้ดจริง รองรับการกด Esc ปิด, ปุ่มคัดลอกโค้ด, และลิงก์เปิด GitHub Blob",
    tags: ["drawer", "inspector", "react", "modal"],
    snippet: "export function SideDrawer({ isOpen, onClose, filePath, fileType, codeContent, isLoading, error }: SideDrawerProps)"
  },
  {
    name: "handleKeyDown (SideDrawer)",
    file: "sidedrawer",
    filePath: "src/components/SideDrawer.tsx",
    line: 36,
    owner: "คน 5",
    category: "Keyboard Navigation",
    badge: "คน 5: Side Drawer (Inspector)",
    signature: "const handleKeyDown = (e: KeyboardEvent) => void",
    desc: "ดักจับปุ่ม Escape เพื่อปิดแผง SideDrawer เมื่อเปิดค้างอยู่",
    tags: ["escape", "keydown", "accessibility", "ux"],
    snippet: "const handleKeyDown = (e: KeyboardEvent) => void"
  },
  {
    name: "handleCopy",
    file: "sidedrawer",
    filePath: "src/components/SideDrawer.tsx",
    line: 58,
    owner: "คน 5",
    category: "Clipboard",
    badge: "คน 5: Side Drawer (Inspector)",
    signature: "const handleCopy = async (): Promise<void>",
    desc: "คัดลอกซอร์สโค้ดที่แสดงอยู่ในแผง SideDrawer ลงใน Clipboard พร้อมเปลี่ยนสถานะปุ่มเป็น Copied ชั่วคราว",
    tags: ["copy", "clipboard", "feedback", "button"],
    snippet: "const handleCopy = async (): Promise<void>"
  },
  {
    name: "getLanguageFromPath",
    file: "codeviewer",
    filePath: "src/lib/code-viewer.ts",
    line: 28,
    owner: "คน 5",
    category: "Syntax Highlighting",
    badge: "คน 5: Code Viewer (Prism)",
    signature: "export function getLanguageFromPath(filePath: string): string",
    desc: "จำแนกภาษาวิเคราะห์จากนามสกุลไฟล์ เช่น .tsx -> tsx, .ts -> typescript, .css -> css เพื่อป้อนให้ PrismJS ไฮไลต์สีได้อย่างถูกต้อง",
    tags: ["extension", "language", "prism", "syntax"],
    snippet: "export function getLanguageFromPath(filePath: string): string"
  },
  {
    name: "formatCodeSnippet",
    file: "codeviewer",
    filePath: "src/lib/code-viewer.ts",
    line: 53,
    owner: "คน 5",
    category: "Performance & Truncation",
    badge: "คน 5: Code Viewer (Prism)",
    signature: "export function formatCodeSnippet(rawCode: string, maxLines: number = 300): FormattedSnippet",
    desc: "ตัดทอนซอร์สโค้ดไม่ให้เกิน 300 บรรทัด เพื่อป้องกันไม่ให้ DOM ค้างเมื่อเปิดไฟล์ขนาดยักษ์ พร้อมระบุว่าโค้ดถูกตัดหรือไม่",
    tags: ["truncate", "maxlines", "performance", "dom"],
    snippet: "export function formatCodeSnippet(rawCode: string, maxLines: number = 300): FormattedSnippet"
  },
  {
    name: "escapeHtml",
    file: "codeviewer",
    filePath: "src/lib/code-viewer.ts",
    line: 81,
    owner: "คน 5",
    category: "Security & Escaping",
    badge: "คน 5: Code Viewer (Prism)",
    signature: "function escapeHtml(text: string): string",
    desc: "แปลงอักขระพิเศษ HTML (&, <, >, \", ') ให้เป็น HTML entities ป้องกันช่องโหว่ XSS เมื่อเรนเดอร์โค้ดดิบ",
    tags: ["xss", "escape", "security", "html"],
    snippet: "function escapeHtml(text: string): string"
  },
  {
    name: "highlightCodeWithPrism",
    file: "codeviewer",
    filePath: "src/lib/code-viewer.ts",
    line: 91,
    owner: "คน 5",
    category: "Syntax Highlighting",
    badge: "คน 5: Code Viewer (Prism)",
    signature: "export function highlightCodeWithPrism(code: string, language: string): string",
    desc: "ใช้ Prism.js แปลงสตริงโค้ดให้เป็น HTML ที่มีคลาสสี syntax highlighting หาก Prism ไม่รองรับจะ fallback ไปใช้ escapeHtml ปลอดภัย 100%",
    tags: ["prism", "highlight", "tokens", "fallback"],
    snippet: "export function highlightCodeWithPrism(code: string, language: string): string"
  },

  // --- คน 6: Pipeline Orchestrator & API Route (src/app/api/analyze/route.ts & src/lib/pipeline.ts) ---
  {
    name: "POST (route.ts)",
    file: "route",
    filePath: "src/app/api/analyze/route.ts",
    line: 7,
    owner: "คน 6",
    category: "API Entry Point & Guard",
    badge: "คน 6: API Route",
    signature: "export async function POST(req: NextRequest): Promise<NextResponse>",
    desc: "API Route หลักของระบบ: รับคำขอ POST ตรวจสอบ Request Body, ดักจับข้อผิดพลาด และส่งต่อไปประมวลผลที่ runAnalysisPipeline",
    tags: ["route", "post", "nextrequest", "api"],
    snippet: "export async function POST(req: NextRequest): Promise<NextResponse>"
  },
  {
    name: "clearPipelineCache",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 60,
    owner: "คน 6",
    category: "Cache Management",
    badge: "คน 6: Core Pipeline",
    signature: "export function clearPipelineCache(): void",
    desc: "ล้าง In-Memory Cache (pipelineCache) ทั้งหมด ใช้สำหรับการรีเซ็ตระบบ หรือใช้ใน Unit/Integration Test เพื่อกันข้อมูลปนเปื้อน",
    tags: ["cache", "clear", "test", "memory"],
    snippet: "export function clearPipelineCache(): void"
  },
  {
    name: "resolveAliasImport",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 66,
    owner: "คน 6",
    category: "Path Resolution",
    badge: "คน 6: Core Pipeline",
    signature: "function resolveAliasImport(rawTarget: string, allFilePaths: string[]): string | null",
    desc: "แปลง Path Alias เช่น @/components/Button หรือ ~/lib/db ให้กลายเป็น Relative Path จริงเทียบกับ src/ หรือรากโปรเจกต์",
    tags: ["alias", "tsconfig", "path", "resolve"],
    snippet: "function resolveAliasImport(rawTarget: string, allFilePaths: string[]): string | null"
  },
  {
    name: "resolveRelativeImport",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 81,
    owner: "คน 6",
    category: "Path Resolution",
    badge: "คน 6: Core Pipeline",
    signature: "function resolveRelativeImport(cleanTarget: string, sourcePath: string, allFilePaths: string[]): string | null",
    desc: "แปลง Relative Import เช่น ../../components/Card โดยคำนวณถอยโฟลเดอร์ตามลำดับเพื่อหาไฟล์ปลายทางจริง",
    tags: ["relative", "dot-dot", "normalize", "path"],
    snippet: "function resolveRelativeImport(cleanTarget: string, sourcePath: string, allFilePaths: string[]): string | null"
  },
  {
    name: "resolveImportToFilePath",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 103,
    owner: "คน 6",
    category: "Path Resolution",
    badge: "คน 6: Core Pipeline",
    signature: "function resolveImportToFilePath(importTarget: string, sourcePath: string, allFilePaths: string[]): string | null",
    desc: "ตัวประสานการแปลง Path: ลองแกะด้วย Alias ก่อน ถ้าไม่ใช่ให้ลอง Relative และ fallback ด้วยการค้นหาชื่อไฟล์แบบ index หรือ นามสกุล .tsx/.ts",
    tags: ["resolver", "extension", "index-file", "lookup"],
    snippet: "function resolveImportToFilePath(importTarget: string, sourcePath: string, allFilePaths: string[]): string | null"
  },
  {
    name: "inferStructuralRelations",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 133,
    owner: "คน 6",
    category: "Structural Heuristics",
    badge: "คน 6: Core Pipeline",
    signature: "export function inferStructuralRelations(filteredFiles: GitHubTreeItem[], allFilePaths: string[]): CodeRelation[]",
    desc: "ฟังก์ชันอัจฉริยะของคน 6: แกะโครงสร้าง Next.js App Router เพื่อสร้างเส้นความสัมพันธ์ระดับโฟลเดอร์โดยไม่ต้องยิง API ดึงโค้ดดิบ (ประหยัด Rate Limit มหาศาล)",
    tags: ["structural", "heuristics", "app-router", "zero-cost"],
    snippet: "export function inferStructuralRelations(filteredFiles: GitHubTreeItem[], allFilePaths: string[]): CodeRelation[]"
  },
  {
    name: "fetchGitHubTree",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 299,
    owner: "คน 6",
    category: "Network & Fallback",
    badge: "คน 6: Core Pipeline",
    signature: "async function fetchGitHubTree(owner: string, repo: string, branch: string, token?: string): Promise<{ items: GitHubTreeItem[]; activeBranch: string }>",
    desc: "ยิงดึง Trees API พร้อมระบบ Auto Fallback: หาก branch main เจอ 404 จะสลับไปลอง branch master ทันทีโดยอัตโนมัติ",
    tags: ["fetch", "github-api", "fallback", "main-master"],
    snippet: "async function fetchGitHubTree(owner: string, repo: string, branch: string, token?: string): Promise<{ items: GitHubTreeItem[]; activeBranch: string }>"
  },
  {
    name: "extractRelationsFromContent",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 374,
    owner: "คน 6",
    category: "Content Analysis & Guard",
    badge: "คน 6: Core Pipeline",
    signature: "function extractRelationsFromContent(file: GitHubTreeItem, content: string, allPaths: string[]): CodeRelation[]",
    desc: "ประสานงานเรียกตัวแกะ imports และ action triggers ของคน 2 พร้อมครอบ try/catch กันพังและแปลง path ให้ตรงกับโหนดในระบบ",
    tags: ["extract", "content", "parser-integration", "safe"],
    snippet: "function extractRelationsFromContent(file: GitHubTreeItem, content: string, allPaths: string[]): CodeRelation[]"
  },
  {
    name: "runAnalysisPipeline",
    file: "pipeline",
    filePath: "src/lib/pipeline.ts",
    line: 439,
    owner: "คน 6",
    category: "Core Orchestrator",
    badge: "คน 6: Core Pipeline",
    signature: "export async function runAnalysisPipeline(githubUrl: string, githubToken?: string): Promise<AnalysisResult>",
    desc: "หัวใจหลักของระบบ: ควบคุมจังหวะ 6 สเต็ป เช็กแคช, ดึง Trees, กรองไฟล์, ดึงโค้ดคู่ขนานพร้อม Timeout 4s, ประกอบโหนดและเส้น, บันทึกแคช และส่งผลลัพธ์",
    tags: ["orchestrator", "pipeline", "concurrency", "timeout", "master-flow"],
    snippet: "export async function runAnalysisPipeline(githubUrl: string, githubToken?: string): Promise<AnalysisResult>"
  }
];

if (typeof window !== "undefined") {
  window.ALL_FUNCTIONS_DIRECTORY = ALL_FUNCTIONS_DIRECTORY;
}
